name: testapp
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  auto_route: ^8.2.0
  get_it: ^8.0.0
  injectable: ^2.5.0
  freezed_annotation: ^2.4.1
  flutter_svg: ^2.0.10+1
  easy_localization: ^3.0.7
  easy_localization_loader: ^2.0.1
  elegant_notification: ^2.1.2
  bloc: ^8.1.4
  flutter_bloc: ^8.1.5
  focus_detector: ^2.0.1
  equatable: ^2.0.5
  hive_flutter: ^1.1.0
  json_annotation: ^4.8.1
  pretty_dio_logger: ^1.3.1
  logger: ^2.2.0
  easy_localization_generator: ^0.3.2
  hive: ^2.2.3
  cached_network_image: ^3.3.1
  lottie: ^3.1.0
  dio_cookie_manager: ^3.1.1
  cookie_jar: ^4.0.8
  shimmer: ^3.0.0
  keyboard_dismisser: ^3.0.0
  rxdart: ^0.28.0
  dio: ^5.4.2+1
  collection: ^1.18.0
  mask_text_input_formatter: ^2.9.0
  smooth_page_indicator: ^1.1.0
  flutter_carousel_widget: ^3.0.1
  csv: ^5.1.1
  path_provider: ^2.1.3
  shared_preferences: ^2.2.3
  geolocator: ^12.0.0
  geocoding: ^3.0.0
  flutter_local_notifications: ^17.1.2
  flutter_background_service: ^5.0.5
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  injectable_generator: ^2.6.1
  build_runner: ^2.4.13
  freezed: ^2.5.2
  auto_route_generator: ^8.0.0
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1
  flutter_gen_runner: ^5.4.0
  flutter_launcher_icons: ^0.13.1


dependency_overrides:
  intl: ^0.19.0
  meta: ^1.11.0


flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/localization/

flutter_launcher_icons:
  image_path: "assets/icons/icon.png"
  android: true
  ios: true

flutter_gen:
  output: lib/common/gen
  integrations:
    flutter_svg: true